# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - ./.env.prod

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
