# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
