# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      PORT: 3000
      NODE_ENV: development

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
